apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "bank-marketing-model"
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      protocolVersion: v2
      storageUri: "pvc://model-storage/bank-marketing/"
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"